# Generated by Django 2.2.7 on 2020-01-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chat_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_room_name', models.CharField(max_length=100)),
                ('port_number', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('type_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_room_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom')),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.UserStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_body', models.TextField(default=None, max_length=400)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('chat_room_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom')),
                ('member_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.MemberStatus'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.User'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=60)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.GroupStatus')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='group_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.Group'),
        ),
    ]
