# Generated by Django 2.2.7 on 2020-01-17 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200114_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoomStatus'),
        ),
    ]
